<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: 'auth' })
const { get, put, post, del } = useAdminApi()
const { data: res, refresh } = await useAsyncData('admin-kategori', () => get<any[]>('/admin/kategori'))
const items = computed(() => res.value?.data ?? [])
const editing = ref<string|null>(null); const editLabel = ref(''); const saving = ref(false)
function startEdit(slug:string,label:string){editing.value=slug;editLabel.value=label}
function cancelEdit(){editing.value=null;editLabel.value=''}
async function saveLabel(slug:string){saving.value=true;try{await put(`/admin/kategori/${slug}`,{label:editLabel.value});editing.value=null;refresh()}catch{}finally{saving.value=false}}
const showCreate = ref(false); const newCat = reactive({slug:'',label:'',group:'belt-conveyor'}); const createError = ref('')
async function createCategory(){createError.value='';try{await post('/admin/kategori',{...newCat});showCreate=false;newCat.slug='';newCat.label='';newCat.group='belt-conveyor';refresh()}catch(e:any){createError.value=e?.data?.error||'Gagal membuat.'}}
async function handleDelete(slug:string,label:string){if(!confirm(`Hapus "${label}"?`))return;await del(`/admin/kategori/${slug}`);refresh()}
</script>
<template>
  <div>
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:24px"><h1 style="font-size:24px;font-weight:700;color:rgb(var(--ink));margin:0;letter-spacing:-0.02em">Kategori Produk</h1><button @click="showCreate=!showCreate" style="background:rgb(var(--accent));color:#fff;padding:10px 20px;border-radius:6px;font-size:13px;font-weight:600;border:none;cursor:pointer;font-family:inherit;letter-spacing:0.01em">{{ showCreate?'Batal':'+ Kategori Baru' }}</button></div>
    <div v-if="showCreate" style="background:#fff;border:1px solid rgb(var(--line));border-radius:10px;padding:20px;margin-bottom:20px">
      <div v-if="createError" style="background:#fef2f2;color:#dc2626;padding:8px 12px;border-radius:6px;font-size:12px;margin-bottom:14px;border:1px solid #fecaca">{{ createError }}</div>
      <div style="display:flex;gap:12px;align-items:flex-end">
        <label style="display:block;flex:1"><span style="font-size:11px;font-weight:600;color:rgb(var(--muted));text-transform:uppercase;letter-spacing:0.08em">Slug</span><input v-model="newCat.slug" placeholder="e.g. rubber-belt" style="display:block;width:100%;margin-top:4px;padding:8px 12px;border:1px solid rgb(var(--line));border-radius:6px;font-size:13px;font-family:inherit;box-sizing:border-box;outline:none" /></label>
        <label style="display:block;flex:1"><span style="font-size:11px;font-weight:600;color:rgb(var(--muted));text-transform:uppercase;letter-spacing:0.08em">Label</span><input v-model="newCat.label" placeholder="e.g. Rubber Belt" style="display:block;width:100%;margin-top:4px;padding:8px 12px;border:1px solid rgb(var(--line));border-radius:6px;font-size:13px;font-family:inherit;box-sizing:border-box;outline:none" /></label>
        <label style="display:block;width:150px"><span style="font-size:11px;font-weight:600;color:rgb(var(--muted));text-transform:uppercase;letter-spacing:0.08em">Group</span><select v-model="newCat.group" style="display:block;width:100%;margin-top:4px;padding:8px 12px;border:1px solid rgb(var(--line));border-radius:6px;font-size:13px;font-family:inherit;background:#fff;box-sizing:border-box;outline:none"><option value="belt-conveyor">Belt Conveyor</option><option value="lainnya">Lainnya</option></select></label>
        <button @click="createCategory" style="padding:9px 20px;background:rgb(var(--accent));color:#fff;border:none;border-radius:6px;font-size:13px;font-weight:600;cursor:pointer;white-space:nowrap;font-family:inherit">Simpan</button>
      </div>
    </div>
    <div style="overflow-x:auto;border-radius:8px;border:1px solid rgb(var(--line));background:#fff"><table style="width:100%;font-size:13px;border-collapse:collapse"><thead><tr style="background:rgb(var(--paper-soft));border-bottom:1px solid rgb(var(--line))"><th style="padding:12px 16px;font-weight:600;color:rgb(var(--muted));text-transform:uppercase;font-size:11px;letter-spacing:0.08em;text-align:left">Slug</th><th style="padding:12px 16px;font-weight:600;color:rgb(var(--muted));text-transform:uppercase;font-size:11px;letter-spacing:0.08em;text-align:left">Label</th><th style="padding:12px 16px;font-weight:600;color:rgb(var(--muted));text-transform:uppercase;font-size:11px;letter-spacing:0.08em;text-align:left">Group</th><th style="padding:12px 16px;font-weight:600;color:rgb(var(--muted));text-transform:uppercase;font-size:11px;letter-spacing:0.08em;text-align:left">Aksi</th></tr></thead>
    <tbody><tr v-for="c in items" :key="c.slug" style="border-bottom:1px solid rgb(var(--line))"><td style="padding:14px 16px;font-family:monospace;font-size:12px;color:rgb(var(--muted))">{{ c.slug }}</td><td style="padding:14px 16px"><input v-if="editing===c.slug" v-model="editLabel" @keyup.enter="saveLabel(c.slug)" @keyup.escape="cancelEdit()" style="width:100%;padding:6px 10px;border:1px solid rgb(var(--line));border-radius:4px;font-size:13px;font-family:inherit;box-sizing:border-box;outline:none" /><span v-else style="font-weight:600;color:rgb(var(--ink))">{{ c.label }}</span></td><td style="padding:14px 16px;color:rgb(var(--muted))">{{ c.group }}</td>
    <td style="padding:14px 16px"><template v-if="editing===c.slug"><button :disabled="saving" @click="saveLabel(c.slug)" style="font-size:12px;color:rgb(var(--accent));background:none;border:none;cursor:pointer;font-family:inherit;font-weight:600;margin-right:10px">Simpan</button><button @click="cancelEdit()" style="font-size:12px;color:rgb(var(--muted));background:none;border:none;cursor:pointer;font-family:inherit">Batal</button></template><template v-else><button @click="startEdit(c.slug,c.label)" title="Edit" style="color:rgb(var(--muted));background:none;border:none;cursor:pointer;padding:4px;border-radius:4px;margin-right:4px"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button @click="handleDelete(c.slug,c.label)" title="Hapus" style="color:rgb(var(--muted));background:none;border:none;cursor:pointer;padding:4px;border-radius:4px"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18"/><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"/><path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/></svg></button></template></td></tr>
    <tr v-if="!items.length"><td colspan="4" style="padding:60px 16px;text-align:center;color:rgb(var(--muted))">Belum ada kategori.</td></tr></tbody></table></div>
  </div>
</template>
